<?php declare(strict_types=1); ?>
<!doctype html><html lang="pt-BR"><head>
<meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<title>5 novidades do Power BI em agosto de 2026 | TECH SANTOS BR</title>
<meta name="description" content="Conheça 5 novidades do Power BI de agosto de 2026: Copilot, atualização seletiva, imagens do OneLake, gráfico de rosca e matriz." />
<link rel="canonical" href="https://techsantos.com.br/blog/novidades-power-bi-agosto-2026.php" />
<meta property="og:type" content="article" /><meta property="og:locale" content="pt_BR" /><meta property="og:url" content="https://techsantos.com.br/blog/novidades-power-bi-agosto-2026.php" />
<meta property="og:title" content="5 novidades do Power BI em agosto de 2026" /><meta property="og:description" content="Copilot, atualização seletiva, OneLake, rosca e matriz: veja o que mudou e como usar." />
<meta property="og:image" content="https://learn.microsoft.com/en-us/power-bi/visuals/media/pie-donut-chart/pie-donut-center-value.png" /><meta name="twitter:card" content="summary_large_image" />
<link rel="icon" type="image/png" href="/assets/img/favicon-32.png" /><link rel="apple-touch-icon" href="/assets/img/apple-touch-icon.png" /><link rel="stylesheet" href="/assets/css/style.css" />
<?php require_once __DIR__ . '/../inc/meta-pixel.php'; require_once __DIR__ . '/../inc/google-analytics.php'; ?>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"5 novidades do Power BI em agosto de 2026","description":"Copilot, atualização seletiva, imagens do OneLake, valor central na rosca e matriz expansível.","datePublished":"2026-09-02","dateModified":"2026-09-02","inLanguage":"pt-BR","author":{"@type":"Person","name":"Clariston Santos"},"publisher":{"@type":"Organization","name":"TECH SANTOS BR","url":"https://techsantos.com.br/"},"mainEntityOfPage":"https://techsantos.com.br/blog/novidades-power-bi-agosto-2026.php"}</script>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"O Copilot lê visuais ocultos no Power BI?","acceptedAnswer":{"@type":"Answer","text":"Sim, quando são revelados por favoritos de exibição acessíveis no relatório. RLS e OLS continuam sendo respeitadas."}},{"@type":"Question","name":"Posso atualizar somente o esquema no Power BI Service?","acceptedAnswer":{"@type":"Answer","text":"Sim. O serviço oferece atualização de esquema e dados, somente esquema ou somente dados, inclusive no nível de tabela."}},{"@type":"Question","name":"Imagens do OneLake podem ser usadas no Power BI?","acceptedAnswer":{"@type":"Answer","text":"Sim. URLs autenticadas do OneLake alimentam diversos visuais, desde que o usuário também tenha permissão no arquivo."}}]}</script>
</head><body>
<header class="site"><div class="nav-row"><a class="brand" href="/"><img src="/assets/img/logo.jpg" alt="Tech Santos BR" /><span>TECH <em>SANTOS BR</em></span></a><nav class="links"><a href="/">Home</a><a href="/curso-power-bi.php">Curso</a><a href="/blog/" aria-current="page">Blog</a><a href="/contato.html">Contato</a><a href="/login.php">Área do Aluno</a></nav><div class="nav-actions"><a class="btn btn-primary desktop-only" href="https://wa.me/5564992905785" target="_blank" rel="noopener">Falar no WhatsApp</a><button class="nav-toggle" aria-label="Abrir menu" aria-expanded="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button></div></div></header>
<main><article class="blog-article">
<div class="blog-meta">Power BI · Publicado em 02/09/2026 · 8 min de leitura</div>
<h1>5 novidades do Power BI em agosto de 2026 que valem testar</h1>
<p>A atualização de agosto de 2026 trouxe mudanças práticas para quem cria, mantém e consome relatórios. Esta seleção evita recursos já abordados no blog e concentra o que pode economizar trabalho agora: uma melhoria do Copilot, controles de atualização, arquivos protegidos e dois ajustes importantes de visualização.</p>
<div class="key-takeaways"><span class="kt-label">Resumo rápido</span><ul><li>O Copilot passou a considerar visuais ocultos por favoritos de exibição.</li><li>Esquema e dados podem ser atualizados separadamente no serviço.</li><li>Imagens autenticadas do OneLake funcionam em vários visuais.</li><li>Rosca e matriz receberam controles que antes exigiam contornos manuais.</li></ul></div>
<h2>1. O Copilot consegue ler visuais ocultos por favoritos?</h2>
<p>Na atualização de agosto de 2026, a Microsoft confirmou que o Resumo do Copilot e o visual Narrativa podem considerar gráficos ocultos por padrão e revelados por um favorito que altera apenas a exibição. O Copilot lê esses visuais sem abrir o favorito nem mudar o estado atual do relatório.</p>
<p>Isso ajuda relatórios com navegação por botões, nos quais vários gráficos ocupam a mesma área. As regras de segurança em nível de linha e objeto continuam sendo aplicadas. Há limites: o favorito precisa estar acessível ao usuário, favoritos pessoais não entram e páginas totalmente ocultas não são consideradas.</p>
<p><strong>Dica prática:</strong> dê títulos claros aos visuais ocultos. O Copilot usa até 20 visuais relevantes e depende dos metadados para escolher o que responde melhor à pergunta.</p>
<h2>2. Como atualizar esquema e dados separadamente?</h2>
<p>Em agosto de 2026, o botão de atualização do Power BI Service passou a oferecer três caminhos: atualizar esquema e dados, sincronizar somente o esquema ou atualizar somente os dados. A operação também pode ser feita por tabela, reduzindo trabalho desnecessário em modelos maiores.</p>
<p>Sincronizar esquema é útil quando uma fonte ganhou uma coluna. Atualizar somente os dados atende situações em que a estrutura continua igual. A escolha exige revisão: renomear ou remover campos pode quebrar medidas DAX, relacionamentos, segurança e visuais dependentes.</p>
<h2>3. Imagens do OneLake podem aparecer no relatório?</h2>
<p>Desde agosto de 2026, URLs de arquivos do OneLake estão disponíveis de forma geral para visuais e mapas do Power BI. Imagens protegidas podem alimentar o visual de imagem, cartões, tabelas, matrizes, segmentações, ícones condicionais e marcadores do Azure Maps.</p>
<p>O ganho é não precisar publicar arquivos anonimamente. O Power BI usa a identidade Microsoft Entra de cada pessoa. Porém, acesso ao relatório ou modelo semântico não concede acesso automático à imagem: o leitor também precisa de permissão no lakehouse, na pasta ou no arquivo.</p>
<p>Não use esse caminho em “Publicar na Web”, pois uma página anônima não consegue autenticar o visitante no OneLake. Se um pipeline de implantação mudar o relatório de ambiente, revise as URLs, que não são reescritas automaticamente.</p>
<h2>4. Como colocar um valor no centro do gráfico de rosca?</h2>
<p>O gráfico de rosca agora possui valor central nativo. Selecione o visual, abra <strong>Formatar visual</strong> e ative <strong>Valor central</strong>. O espaço pode mostrar o total do gráfico ou uma medida personalizada, com controle de fonte, unidade, rótulo, imagem e fundo.</p>
<figure style="margin:2rem 0"><img src="https://learn.microsoft.com/en-us/power-bi/visuals/media/pie-donut-chart/pie-donut-center-value.png" alt="Captura oficial do Power BI com valor central ativado no gráfico de rosca" loading="lazy" style="width:100%;height:auto;border:1px solid var(--line);border-radius:8px;background:#fff" /><figcaption style="font-size:.78rem;color:var(--ink-faint);margin-top:.6rem">Valor central no gráfico de rosca. Fonte: Microsoft Learn.</figcaption></figure>
<p>O valor responde a filtros, realces cruzados, drill-down e seleção de fatias. Assim, ele permanece alinhado e acessível sem sobrepor um cartão. A opção é exclusiva da rosca; o gráfico de pizza não oferece valor central.</p>
<h2>5. A matriz pode expandir os cabeçalhos das colunas?</h2>
<p>Sim. Em agosto de 2026, expandir e recolher níveis no cabeçalho das colunas da matriz chegou à disponibilidade geral. Quando existem dois ou mais campos na área <strong>Colunas</strong>, ícones de mais e menos permitem navegar pela hierarquia dentro do próprio visual.</p>
<p>O autor controla cor e tamanho em <strong>Cabeçalhos de coluna &gt; ícones +/-</strong>. Também pode ativar a expansão automática de linhas e colunas. Um uso direto é mostrar ano, trimestre e mês sem abrir todas as combinações de uma vez.</p>
<h2>Qual novidade testar primeiro?</h2>
<p>Comece pelo problema mais frequente. Se a manutenção do modelo consome tempo, teste a atualização seletiva. Se o relatório usa navegação por favoritos, valide o Copilot. Para relatórios operacionais, valor central e expansão de colunas entregam uma melhoria visível com pouco esforço.</p>
<p>Todos esses recursos dependem de versão, licença, capacidade e configuração compatíveis. Use a versão mais recente do Power BI Desktop e confira as exigências do seu ambiente antes de planejar uma entrega.</p>
<div class="blog-cta"><h2>Quer aplicar isso no seu relatório?</h2><p>Leve sua dúvida para uma aula particular ou conheça gratuitamente a didática do curso completo de Power BI.</p><div class="hero-cta"><a class="btn btn-primary" href="/aulas-particulares-power-bi.php?utm_source=blog&amp;utm_medium=organic&amp;utm_campaign=powerbi_agosto_2026">Ver aulas particulares</a><a class="btn btn-ghost" href="/aula-gratis.php?utm_source=blog&amp;utm_medium=organic&amp;utm_campaign=powerbi_agosto_2026">Assistir 3 aulas grátis</a></div></div>
<h2>Perguntas frequentes</h2><div class="blog-faq-grid"><div class="faq-item"><h3>O Copilot lê qualquer item oculto?</h3><p>Não. A novidade cobre visuais ligados a favoritos de exibição acessíveis. Favoritos pessoais e páginas ocultas têm limitações.</p></div><div class="faq-item"><h3>Atualizar somente dados altera o esquema?</h3><p>Não. Use a opção de esquema quando precisar incorporar mudanças estruturais da fonte.</p></div><div class="faq-item"><h3>O usuário precisa acessar o OneLake?</h3><p>Sim. A identidade do leitor precisa ter permissão para carregar o arquivo protegido.</p></div></div>
<p style="margin-top:2.5rem;font-size:.82rem;color:var(--ink-faint)">Fontes oficiais: <a href="https://learn.microsoft.com/en-nz/power-bi/fundamentals/whats-new" target="_blank" rel="noopener">atualização de agosto de 2026</a>, <a href="https://learn.microsoft.com/en-us/power-bi/explore-reports/copilot-pane-summarize-content" target="_blank" rel="noopener">resumos com Copilot</a>, <a href="https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data" target="_blank" rel="noopener">atualização de dados</a>, <a href="https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-onelake-files" target="_blank" rel="noopener">arquivos do OneLake</a>, <a href="https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-pie-donut-chart" target="_blank" rel="noopener">gráficos de rosca</a> e <a href="https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-matrix-visual" target="_blank" rel="noopener">matriz</a>. Consultadas em 02/09/2026.</p>
</article></main>
<footer class="site footer-wide"><div class="container"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="/"><img src="/assets/img/logo.jpg" alt="Tech Santos BR" /><span>TECH <em>SANTOS BR</em></span></a><p>Consultoria, treinamento e aulas particulares em Power BI, Excel e Microsoft Fabric.</p></div><div class="footer-col"><h4>Curso</h4><a href="/curso-power-bi.php">Curso completo</a><a href="/aula-gratis.php">Aula grátis</a><a href="/aulas-particulares-power-bi.php">Aulas particulares</a></div><div class="footer-col"><h4>Empresa</h4><a href="/sobre.html">Sobre</a><a href="/servicos.html">Serviços</a><a href="/blog/">Blog</a></div><div class="footer-col"><h4>Contato</h4><a href="mailto:claristonsantos@techsantos.com.br">claristonsantos@techsantos.com.br</a><a href="https://wa.me/5564992905785">(64) 99290-5785</a></div></div><div class="footer-bottom"><span>© 2026 TECH SANTOS BR · CNPJ 41.135.509/0001-29</span></div></div></footer>
<script src="/assets/js/nav.js"></script></body></html>
