# -*- coding: utf-8 -*-
"""Correções fonéticas para termos que o edge-tts (voz pt-BR-AntonioNeural)
lê errado em português. Cada uma foi confirmada por ouvido pelo usuário,
comparando opções lado a lado antes de aplicar.

Aplicar SOMENTE ao texto que vai para o motor de TTS, nunca às legendas
ou texto exibido na tela (que devem continuar com a grafia correta).
"""
import re

PRONUNCIATION_FIXES = [
    (r"\bPower BI\b", "Páuer Bi Ai"),
    (r"\bBR\b", "Bê Erre"),
    (r"\bPROCV\b", "PROC Vê"),
    (r"\bPROCX\b", "PROC Xis"),
    (r"\bDAX\b", "Dáks"),
    (r"\bdashboards\b", "déshibórdis"),
    (r"\bdashboard\b", "déshibórdi"),
    (r"\bControl T\b", "Control Tê"),
    (r"\bCtrl\+T\b", "Control Tê"),
    (r"\bDirectQuery\b", "Dairét Cuéri"),
    (r"\bCopilot\b", "Cópaylôt"),
    (r"\bPython\b", "Páiton"),
    (r"\bField [Pp]arameters\b", "Fiuld Páramiters"),
    # Termos do Microsoft Fabric — teste A/B com o usuário em 2026-09-26
    # (28 termos). Só entram aqui os que ele escolheu a alternativa (B); os
    # demais soaram bem na leitura padrão e ficam sem substituição:
    # Microsoft Fabric, OneLake, Spark, T-SQL, SKU, F64, CUs, PPU, workspace,
    # pipeline, Parquet, Purview, Direct Lake, Power Query.
    # Plurais usam a mesma grafia aprovada do singular (não foram testados à
    # parte). PySpark antes de Spark para a regra específica vencer.
    (r"\bPySpark\b", "Pái Ispárk"),
    (r"\b[Ll]akehouses?\b", "Lêique ráus"),
    (r"\b[Ww]arehouses?\b", "Uér ráus"),
    (r"\b[Ee]venthouses?\b", "Ivent ráus"),
    (r"\b[Ee]ventstreams?\b", "Ivent strím"),
    (r"\bKQL\b", "Ká Quê Éle"),
    (r"\b[Nn]otebooks?\b", "nôut búk"),
    (r"\bDataflows? Gen ?2\b", "Dêita flôu Gen dois"),
    (r"\bDelta Lake\b", "Délta Lêique"),
    (r"\bApache Airflow\b", "Apáche Ér flôu"),
    (r"\bAirflow\b", "Ér flôu"),
    (r"\bData Factory\b", "Dêita Féctori"),
    (r"\bReal-Time Intelligence\b", "Riál Taime Intélidjens"),
    (r"\bSaaS\b", "Sáss"),
    (r"\bOLTP\b", "Ó Éle Tê Pê"),
    # Segundo teste A/B (2026-09-26, 30 termos dos módulos 2-3). Ficaram na
    # leitura padrão: V-Order, SCD, MERGE, CDC, upsert, Iceberg, Scala,
    # Amazon S3, TMSL, SSMS, RLS, BigQuery, Cosmos DB, PostgreSQL, MySQL,
    # Microsoft Entra. "ADLS Gen2" reaproveita o "Gen dois" já aprovado.
    (r"\bOPTIMIZE\b", "Óptimaiz"),
    (r"\bVACUUM\b", "Vácuum"),
    (r"\bETL\b", "Ê Tê Éle"),
    (r"\bIDENTITY\b", "Aidêntiti"),
    (r"\b[Ss]taging\b", "stêidjin"),
    (r"\b[Ss]nowflake\b", "snôu flêik"),
    (r"\btime travel\b", "taime trével"),
    (r"\bADLS Gen ?2\b", "Á Dê Éle Ésse Gen dois"),
    (r"\bADLS\b", "Á Dê Éle Ésse"),
    (r"\bXMLA\b", "Xis Éme Éle Á"),
    (r"\bDatabricks\b", "Dêita bríks"),
    (r"\bJSON Lines\b", "Djêison Láins"),  # rodada 4; antes da regra de JSON
    (r"\bJSON\b", "Djêison"),
    (r"\bCSV\b", "Cê Ésse Vê"),
    (r"\bdbo\b", "Dê Bê Ó"),
    # Terceiro teste A/B (2026-09-26, 38 termos do módulo 4 - Data Factory).
    # Ficaram na leitura padrão: Copy job, On success, On fail, VNet,
    # ISO 8601, Outlook, concat, exit, ARM, REST, ADF.
    # "Do-if-skip-else" junta as grafias aprovadas de Do-if-else e On skip.
    (r"\bLookup\b", "Lúk âp"),
    (r"\bForEach\b", "Fór ítch"),
    (r"\b(Switch|SWITCH)\b", "Suítch"),  # maiúsculas (DAX) usam a grafia aprovada
    (r"\bUntil\b", "Ântil"),
    (r"\bWebhook\b", "Uéb húk"),
    (r"\bwatermark\b", "uóter márk"),
    (r"\btry-catch\b", "trái kétch"),
    (r"\bDo-if-skip-else\b", "Dú if iskíp élse"),
    (r"\bDo-if-else\b", "Dú if élse"),
    (r"\bOn completion\b", "Ón compliíchon"),
    (r"\bOn skip\b", "Ón iskíp"),
    (r"\bActivator\b", "Éctiveitor"),
    (r"\bReflex\b", "Rífléks"),
    (r"\bGantt\b", "Gânt"),
    (r"\bChange Data Feed\b", "Tchêindj Dêita Fíd"),
    (r"\bGUIDs\b", "Gú íds"),
    (r"\bGUID\b", "Gú íd"),
    (r"\bSHIR\b", "Ésse Agá Í Érre"),
    (r"\bPrivate Link\b", "Práivet Link"),
    (r"\bELT\b", "Ê Éle Tê"),
    (r"\bUTC\b", "U Tê Cê"),
    (r"\bTeams\b", "Tíms"),
    (r"\bDAGs?\b", "Dégs"),
    (r"\bKafka\b", "Káfka"),
    (r"\bformatDateTime\b", "fórmat Dêit Táime"),
    (r"\butcNow\b", "U Tê Cê Nau"),
    (r"\baddDays\b", "éd Dêis"),
    (r"\bSynapse\b", "Sináps"),
    (r"\bCapacity Metrics\b", "Capáciti Métrics"),
    # Quarto teste A/B (2026-09-27, 32 termos do módulo 5 - Dataflows Gen2).
    # Ficaram na leitura padrão: PQT, DateTime, Excel, SharePoint, Oracle,
    # DDL, DML, SELECT, ORDER BY, DELETE, null, CI/CD, Git.
    (r"\bDataflowsStagingLakehouse\b", "Dêita flôus Stêidjin Lêique ráus"),
    (r"\bDataflow Gen ?1\b", "Dêita flôu Gen um"),
    (r"\bDataflows\b", "Dêita flôus"),
    (r"\bDataflow\b", "Dêita flôu"),
    (r"\blinguagem M\b", "linguagem Éme"),
    (r"\bfast copy\b", "fést cópi"),
    (r"\bquery folding\b", "cuéri fôlding"),
    (r"\bbuckets\b", "bâkets"),
    (r"\bbucket\b", "bâket"),
    (r"\bDateTimeZone\b", "Dêit Táime Zôun"),
    (r"\bfuzzy\b", "fâzi"),
    (r"\bAzure Data Explorer\b", "Ájur Dêita Explórer"),
    (r"\bZIP\b", "Zíp"),
    (r"\bINSERT\b", "Insért"),
    (r"\bUPDATE\b", "Âpdeit"),
    (r"\bCREATE\b", "Criêit"),
    (r"\bALTER\b", "Ólter"),
    (r"\bDataSource\.NotFound\b", "Dêita Sórs Nót Fáund"),
    (r"\bFormula\.Firewall\b", "Fórmula Fáier uól"),
    # Quinto teste A/B (2026-09-27, 50 termos do módulo 6 - Spark). Ficaram na
    # leitura padrão: driver, SparkR, Spark SQL, Livy, withColumn, append,
    # dense rank, PyPI, Autotune, broadcast. Nomes em <code> chegam aqui com
    # "_" trocado por espaço (curso_audio._codigo_falado), por isso [_ ].
    (r"\bpools\b", "púls"),
    (r"\bpool\b", "púl"),
    (r"\bMarkdown\b", "Márk dáun"),
    (r"\bJupyter\b", "Djúpiter"),
    (r"\bnotebookutils\b", "nôut búk iútils"),
    (r"\bMSSparkUtils\b", "Ém Ésse Spárk iútils"),
    (r"\bDataFrames\b", "Dêita Frêims"),
    (r"\bDataFrame\b", "Dêita Frêim"),
    (r"\bdisplay\b", "displêi"),
    (r"\bgroupBy\b", "grúp bái"),
    (r"\bsaveAsTable\b", "sêiv éz têibol"),
    (r"\boverwrite\b", "ôver ráit"),
    (r"\bpartitionBy\b", "partíchon bái"),
    (r"\bleft[_ ]anti\b", "léft ênti"),
    (r"\brow[_ ]number\b", "rôu nâmber"),
    (r"\blag\b", "lég"),
    (r"\blead\b", "líd"),
    (r"\bdropDuplicates\b", "dróp dúplikeits"),
    (r"\bfillna\b", "fil ené"),
    (r"\bcoalesce\b", "côualéss"),
    (r"\bConda\b", "Cônda"),
    (r"\bMaven\b", "Mêiven"),
    (r"\brunMultiple\b", "rân múltipol"),
    (r"\breadStream\b", "ríd strím"),
    (r"\bwriteStream\b", "ráit strím"),
    (r"\bcheckpoints\b", "tchék póints"),
    (r"\bcheckpoint\b", "tchék póint"),
    (r"\bprocessingTime\b", "prócessing táime"),
    (r"\bavailableNow\b", "avêilabol náu"),
    (r"\btumbling\b", "tâmbling"),
    (r"\bsliding\b", "sláiding"),
    (r"\bwithWatermark\b", "uíth uóter márk"),
    (r"\bskew\b", "iskiú"),
    (r"\bTooManyRequestsForCapacity\b", "Tú Méni Riquésts Fór Capáciti"),
    (r"\b[Vv]Cores\b", "Vê Córs"),
    (r"\bburst\b", "bârst"),
    (r"\bFIFO\b", "Fáifo"),
    (r"\bVelox\b", "Vélocs"),
    (r"\b(Apache )?Gluten\b", "Apáche Glúten"),
    (r"\bshuffle\b", "xâfol"),
    (r"\btoPandas\b", "tu pândas"),
    (r"\bPolars\b", "Pôlars"),
    (r"\boptimize write\b", "óptimaiz ráit"),
    (r"\bSpark Advisor\b", "Spárk Edváizor"),
    # Sexto teste A/B (2026-09-27, 47 termos do módulo 7 - Warehouse/T-SQL).
    # Ficaram na leitura padrão: WHERE, HAVING, TOP, bigint, OVER, RANK,
    # BEGIN TRAN, COMMIT, AS CLONE OF. IDENTITY_INSERT (B) já sai certo pela
    # combinação das regras de IDENTITY e INSERT.
    (r"\bJOIN\b", "Djóin"),
    (r"\bGROUP BY\b", "Grúp Bái"),
    (r"\bTRUNCATE\b", "Trânkeit"),
    (r"\bDROP\b", "Dróp"),
    (r"\bCOPY INTO\b", "Cópi Íntu"),
    (r"\bCTAS\b", "Cê Tê Á Ésse"),
    (r"\bOPENROWSET\b", "Ópen Rôu Sét"),
    (r"\bDBCC CHECKIDENT\b", "Dê Bê Cê Cê Tchék Aidént"),
    (r"\bRESEED\b", "Rissíd"),
    (r"\bNOT ENFORCED\b", "Nót Enfórst"),
    (r"\bNONCLUSTERED\b", "Nón Clâsterd"),
    (r"\bCLUSTER BY\b", "Clâster Bái"),
    (r"\bnvarchar\b", "ên var char"),
    (r"\bvarchar\b", "var char"),
    (r"\bdatetime2\b", "dêit táime dois"),
    (r"\buniqueidentifier\b", "iuníque aidêntifaier"),
    (r"\bcollation\b", "colêichon"),
    (r"\bLatin1_General_100_BIN2_UTF8\b", "Látin um Djeneral cem Bin dois U Tê Éfe oito"),
    (r"\bCTEs\b", "Cê Tê Ís"),
    (r"\bCTE\b", "Cê Tê Í"),
    (r"\bPARTITION BY\b", "Partíchon Bái"),
    (r"\bLAG\b", "Lég"),
    (r"\bCOALESCE\b", "Côualéss"),
    (r"\bROLLBACK\b", "Rôul Bék"),
    (r"\bsnapshot\b", "isnép xót"),
    (r"\btempdb\b", "temp Dê Bê"),
    (r"\bFOR TIMESTAMP AS OF\b", "Fór Táime Stémp Éz Óf"),
    (r"\bQuery Insights\b", "Cuéri Ínsaits"),
    (r"\bqueryinsights\b", "cuéri ínsaits"),
    (r"\bDMVs\b", "Dê Éme Vês"),
    (r"\bDMV\b", "Dê Éme Vê"),
    (r"\bKILL\b", "Kíl"),
    (r"\bsys[ .]dm[ _]exec[ _]requests\b", "sis dê éme ecsec riquésts"),
    (r"\bSSMS\b", "Ésse Ésse Éme Ésse"),
    (r"\bVS Code\b", "Vê Ésse Côud"),
    (r"\bMPP\b", "Éme Pê Pê"),
    (r"\bsp[_ ]rename\b", "ésse pê rinêim"),
    (r"\bstored procedures?\b", "stórd prossídjur"),
    (r"\binline\b", "in láin"),
    # Sétimo teste A/B (2026-09-27, 39 termos do módulo 8 - Real-Time/KQL).
    # Ficaram na leitura padrão: hub, Event Grid, Google Pub/Sub, Kusto, ago,
    # project, IsTransactional. Operadores KQL só em minúsculas (como no
    # código) para não pegar palavras soltas em outros contextos.
    (r"\bIoT Hub\b", "Ái Ô Tí Râb"),
    (r"\bService Bus\b", "Sérvis Bâs"),
    (r"\bKinesis\b", "Kinísis"),
    (r"\bMSK\b", "Éme Ésse Cá"),
    (r"\bMQTT\b", "Éme Quê Tê Tê"),
    (r"\bSolace\b", "Sólas"),
    (r"\bMongoDB\b", "Mongo Dê Bê"),
    (r"\bConfluent\b", "Cónfluent"),
    (r"\bhopping\b", "róping"),
    (r"\bSystem[ .]Timestamp\b", "Sístem Táime Stémp"),
    (r"\b[Tt]imestamp\b", "Táime Stémp"),
    (r"\bexternal[_ ]table\b", "ekstérnal têibol"),
    (r"\bsummarize\b", "sâmaraiz"),
    (r"\bbin\b", "bín"),
    (r"\bextend\b", "ekstênd"),
    (r"\btake[_ ]any\b", "têik éni"),
    (r"\btake\b", "têik"),
    (r"\brender\b", "rênder"),
    (r"\btimechart\b", "táime tchárt"),
    (r"\bhas\b", "réz"),
    (r"\bcontains\b", "contêins"),
    (r"\barg[_ ]max\b", "arg máks"),
    # "serialize" também é verbo em português ("serialize as cargas"):
    # só troca quando é o operador KQL.
    (r"\boperador serialize\b", "operador sírializ"),
    (r"\bprev\b", "prév"),
    (r"\brow[_ ]cumsum\b", "rôu cúm sâm"),
    (r"\bmake-series\b", "mêik síris"),
    (r"\bdcount\b", "dê count"),
    (r"\bbackfill\b", "békfil"),
    (r"\bPower Automate\b", "Páuer Óutomeit"),
    (r"\.?\bshow ingestion failures\b", "xôu ingéstchon fêiliurs"),
    (r"\bAzure Monitor\b", "Ájur Mônitor"),
    (r"\bApplication Insights\b", "Aplikêichon Ínsaits"),
    # Oitavo teste A/B (2026-09-27, 22 termos do módulo 9 - modelos semânticos).
    # Ficaram na leitura padrão: Dual, live connection, YoY.
    (r"\bVertiPaq\b", "Vérti Pék"),
    (r"\bImport\b", "Ímport"),
    (r"\bSELECTEDMEASURE\b", "Selékted Méjur"),
    (r"\bUSERELATIONSHIP\b", "Iuz Rilêichonchip"),
    (r"\bCROSSFILTER\b", "Crós Filter"),
    (r"\bISFILTERED\b", "Iz Filtered"),
    (r"\bCALCULATE\b", "Cálculeit"),
    (r"\bDATESYTD\b", "Dêits Uai Tê Dê"),
    (r"\bSAMEPERIODLASTYEAR\b", "Sêim Píriod Lést Íer"),
    (r"\bDIVIDE\b", "Diváid"),
    (r"\bFORMAT\b", "Fórmat"),
    (r"\bNAMEOF\b", "Nêim Óf"),
    (r"\bCALENDARAUTO\b", "Calêndar Óuto"),
    (r"\bCALENDAR\b", "Calêndar"),
    (r"\bCOUNTROWS\b", "Cáunt Rôus"),
    (r"\bTMDL\b", "Tê Éme Dê Éle"),
    (r"\bQ&A\b", "Quiú en Ei"),
    (r"\bjunk\b", "djânk"),
    (r"\bDesktop\b", "Désktop"),
    # Nono teste A/B (2026-09-27, 49 funções DAX do módulo 10): todas B.
    # Só em maiúsculas, como aparecem no DAX.
    (r"\bKEEPFILTERS\b", "Kíp Filters"),
    (r"\bREMOVEFILTERS\b", "Rimúv Filters"),
    (r"\bALLEXCEPT\b", "Ól Eksépt"),
    (r"\bALLSELECTED\b", "Ól Seléctid"),
    (r"\bALL\b", "Ól"),
    (r"\bFILTER\b", "Filter"),
    (r"\bVALUES\b", "Váliús"),
    (r"\bDISTINCT\b", "Distínkt"),
    (r"\bTREATAS\b", "Trít Éz"),
    (r"\bCALCULATETABLE\b", "Cálculeit Têibol"),
    (r"\bSUMX\b", "Sâm Éks"),
    (r"\bAVERAGEX\b", "Éverêdj Éks"),
    (r"\bRANKX\b", "Rénk Éks"),
    (r"\bCONCATENATEX\b", "Concatenêit Éks"),
    (r"\bTOTALYTD\b", "Tôtal Uai Tê Dê"),
    (r"\bDATEADD\b", "Dêit Éd"),
    (r"\bPARALLELPERIOD\b", "Péralel Píriod"),
    (r"\bDATESINPERIOD\b", "Dêits In Píriod"),
    (r"\bPREVIOUSMONTH\b", "Príviôs Mânth"),
    (r"\bOFFSET\b", "Ófset"),
    (r"\bWINDOW\b", "Uíndou"),
    (r"\bINDEX\b", "Índex"),
    (r"\bROWNUMBER\b", "Rôu Nâmber"),
    (r"\bORDERBY\b", "Órder Bái"),
    (r"\bPARTITIONBY\b", "Partíchon Bái"),
    (r"\bREL\b", "Rél"),
    (r"\bRUNNINGSUM\b", "Râning Sâm"),
    (r"\bMOVINGAVERAGE\b", "Múving Éverêdj"),
    (r"\bPREVIOUS\b", "Príviôs"),
    (r"\bHIGHESTPARENT\b", "Ráiest Pérent"),
    (r"\bHASONEVALUE\b", "Réz Uân Váliu"),
    (r"\bSELECTEDVALUE\b", "Selékted Váliu"),
    (r"\bISCROSSFILTERED\b", "Iz Crós Filtered"),
    (r"\bISINSCOPE\b", "Iz In Scôup"),
    (r"\bUSERPRINCIPALNAME\b", "Iúzer Príncipal Nêim"),
    (r"\bISBLANK\b", "Iz Blénk"),
    (r"\bBLANK\b", "Blénk"),
    (r"\bINFO\b", "Ínfo"),
    (r"\bCOLUMNSTATISTICS\b", "Cólum Statístics"),
    (r"\bEVALUATE\b", "Iváliueit"),
    (r"\bDEFINE\b", "Difáin"),
    (r"\bMEASURE\b", "Méjur"),
    (r"\bSTART AT\b", "Stárt Ét"),
    (r"\bSUMMARIZECOLUMNS\b", "Sâmaraiz Cóluns"),
    (r"\bTOPN\b", "Tóp Én"),
    (r"\bADDCOLUMNS\b", "Éd Cóluns"),
    (r"\bSELECTCOLUMNS\b", "Selékt Cóluns"),
    (r"\bTRUE\b", "Trú"),
    (r"\bVAR\b", "Vár"),
    (r"\bRETURN\b", "Ritârn"),
    # Décimo teste A/B (2026-09-27, 16 termos do módulo 11 - Direct Lake).
    # Ficaram na leitura padrão: DirectLakeBehavior, DirectLakeOnly,
    # DirectQueryOnly, SSO, TOM, RangeStart, RangeEnd, SQL Server Profiler.
    (r"\bframing\b", "frêiming"),
    (r"\bDirectLakeFallbackInfo\b", "Dairét Lêique Fólbék Ínfo"),
    (r"\bfallback\b", "fólbék"),
    (r"\bTABLETRAITS\b", "Têibol Treits"),
    (r"\bguardrails\b", "gárd rêils"),
    (r"\bDáks Studio\b", "Dáks Stúdio"),  # "DAX" já virou "Dáks" pela regra acima
    (r"\bIFERROR\b", "If Érror"),
    (r"\bISERROR\b", "Iz Érror"),
    # Décimo primeiro teste A/B (2026-09-27, 22 termos do módulo 12 -
    # segurança). Ficaram na leitura padrão: ReadAll, Build, GRANT, email().
    # CREATE e ALTER já foram trocados pelas regras acima, por isso aqui só
    # entra o resto da expressão (ROLE, SECURITY POLICY, ANY MASK).
    (r"\bReadData\b", "Ríd Dêita"),
    (r"\bReshare\b", "Ri Xér"),
    (r"\bDENY\b", "Dinái"),
    (r"\bREVOKE\b", "Rivôuk"),
    (r"\bROLE\b", "Rôul"),
    (r"\bSECURITY POLICY\b", "Sekiúriti Pólici"),
    (r"\bUSER[_ ]NAME\b", "Iúzer Nêim"),
    (r"\bSCHEMABINDING\b", "Squêma Báinding"),
    (r"\bMASKED WITH\b", "Mésqued Uíth"),
    (r"\bUNMASK\b", "Ân Mésk"),
    (r"\bANY MASK\b", "Éni Mésk"),
    (r"\brandom\(\)", "rêndom"),
    (r"\bpartial\(\)", "párchal"),
    (r"\bCLS\b", "Cê Éle Ésse"),
    (r"\bOLS\b", "Ó Éle Ésse"),
    (r"\bmetadataPermission\b", "Métadêita Permíchon"),
    (r"\bTabular Editor\b", "Tâbiular Éditor"),
    (r"\bMicrosoft 365\b", "Máicrossoft trezentos e sessenta e cinco"),
    # Décimo segundo teste A/B (2026-09-27, 20 termos do módulo 13 - ciclo
    # de vida). Ficaram na leitura padrão: branch, SQL Database Projects.
    # Extensões aparecem com ponto no texto e sem ponto dentro de <code>.
    (r"\bGitHub Actions\b", "Guít Râb Ékchons"),
    (r"\bGitHub\b", "Guít Râb"),
    (r"\bAzure DevOps\b", "Ájur Dév Óps"),
    (r"\bcommit\b", "comít"),
    (r"\bpull requests?\b", "púl riquést"),
    (r"\bpush\b", "púch"),
    (r"\.?\bpbip\b", " ponto Pê Bê Í Pê"),
    (r"\.?\bpbix\b", " ponto Pê Bê Í Xis"),
    (r"\.?\bpbit\b", " ponto Pê Bê Í Tê"),
    (r"\.?\bpbids\b", " ponto Pê Bê Í Dê Ésse"),
    (r"\bPBIR\b", "Pê Bê Í Érre"),
    (r"\bmodel[. ]bim\b", "môdel bím"),
    (r"\bdefinition\b", "defíníchon"),
    (r"\.?\bsqlproj\b", " ponto És Quê Éle Prój"),
    (r"\bDacFx\b", "Dék Éfe Xis"),
    (r"\bSqlPackage\b", "És Quê Éle Pékedj"),
    (r"\bALM Toolkit\b", "Á Éle Éme Tul Kít"),
    (r"\.?\bgitignore\b", " ponto guít ignór"),
    # "Agora" foi testado em 2026-07-14 (3 opções comparadas) e a pronúncia
    # padrão do edge-tts já soa correta - não precisa de substituição.
    # Mantido documentado aqui para não ser re-testado à toa depois.
]


def fix_pronunciation(text: str) -> str:
    for pattern, replacement in PRONUNCIATION_FIXES:
        text = re.sub(pattern, replacement, text)
    return text
